/**
 * Default kudos granted to a user.
 */
export const DEFAULT_KUDOS = 200 as const;

/**
 * Supported reaction emojis.
 */
export const REACTION_EMOJIS = ['👍', '❤️', '😂', '🔥', '😎'] as const;

/**
 * Type of supported reaction emoji.
 */
export type ReactionEmoji = (typeof REACTION_EMOJIS)[number];

export const EMOJI_SHORTCUTS: Record<string, string> = {
	// 😀 Faces
	':smile:': '😊',
	':grin:': '😁',
	':laugh:': '😂',
	':joy:': '🤣',
	':wink:': '😉',
	':blush:': '😊',
	':happy:': '😃',
	':cool:': '😎',
	':love:': '😍',
	':kiss:': '😘',
	':yum:': '😋',
	':thinking:': '🤔',
	':confused:': '😕',
	':neutral:': '😐',
	':sad:': '😔',
	':cry:': '😢',
	':sob:': '😭',
	':angry:': '😠',
	':rage:': '😡',
	':surprised:': '😲',
	':shocked:': '😳',
	':sleepy:': '😴',
	':tired:': '😩',
	':sick:': '🤢',
	':mask:': '😷',
	':dead:': '💀',
	':ghost:': '👻',
	':clown:': '🤡',
	':robot:': '🤖',
	':nerd:': '🤓',
	':money:': '🤑',
	':mindblown:': '🤯',
	':relieved:': '😌',
	':sweat:': '😅',
	':winkwink:': '😜',
	':halo:': '😇',
	':devil:': '😈',
	':plead:': '🥺',
	':zip:': '🤐',

	// 🙌 Gestures
	':wave:': '👋',
	':clap:': '👏',
	':pray:': '🙏',
	':ok:': '👌',
	':thumbsup:': '👍',
	':thumbsdown:': '👎',
	':fist:': '✊',
	':victory:': '✌️',
	':crossed:': '🤞',
	':muscle:': '💪',
	':pointup:': '☝️',
	':pointdown:': '👇',
	':pointright:': '👉',
	':pointleft:': '👈',
	':handshake:': '🤝',

	// ❤️ Love & Emotions
	':heart:': '❤️',
	':heartbreak:': '💔',
	':sparkleheart:': '💖',
	':blueheart:': '💙',
	':greenheart:': '💚',
	':yellowheart:': '💛',
	':purpleheart:': '💜',
	':blackheart:': '🖤',
	':whiteheart:': '🤍',
	':giftheart:': '💝',

	// 🎉 Celebrations
	':party:': '🎉',
	':tada:': '🎊',
	':confetti:': '🎊',
	':cake:': '🎂',
	':birthday:': '🎂',
	':gift:': '🎁',
	':fireworks:': '🎆',
	':sparkles:': '✨',
	':star:': '⭐',
	':boom:': '💥',
	':trophy:': '🏆',
	':medal:': '🥇',
	':ribbon:': '🎀',

	// 🌍 Nature & Weather
	':sun:': '☀️',
	':moon:': '🌙',
	':star2:': '🌟',
	':fire:': '🔥',
	':rain:': '🌧️',
	':snow:': '❄️',
	':cloud:': '☁️',
	':zap:': '⚡',
	':rainbow:': '🌈',
	':tree:': '🌳',
	':flower:': '🌸',
	':rose:': '🌹',
	':leaf:': '🍃',
	':cactus:': '🌵',
	':mushroom:': '🍄',
	':waveocean:': '🌊',
	':mountain:': '🏔️',

	// 🍔 Food
	':pizza:': '🍕',
	':burger:': '🍔',
	':fries:': '🍟',
	':hotdog:': '🌭',
	':taco:': '🌮',
	':burrito:': '🌯',
	':sandwich:': '🥪',
	':rice:': '🍚',
	':noodles:': '🍜',
	':sushi:': '🍣',
	':cookie:': '🍪',
	':chocolate:': '🍫',
	':icecream:': '🍦',
	':coffee:': '☕',
	':tea:': '🍵',
	':beer:': '🍺',
	':wine:': '🍷',
	':cocktail:': '🍸',
	':juice:': '🧃',

	// 🐶 Animals
	':dog:': '🐶',
	':cat:': '🐱',
	':mouse:': '🐭',
	':rabbit:': '🐰',
	':bear:': '🐻',
	':panda:': '🐼',
	':tiger:': '🐯',
	':lion:': '🦁',
	':fox:': '🦊',
	':monkey:': '🐵',
	':chicken:': '🐔',
	':penguin:': '🐧',
	':unicorn:': '🦄',
	':dragon:': '🐉',
	':butterfly:': '🦋',
	':fish:': '🐟',
	':whale:': '🐋',

	// 🚗 Objects & Travel
	':car:': '🚗',
	':bike:': '🚲',
	':bus:': '🚌',
	':train:': '🚆',
	':airplane:': '✈️',
	':ship:': '🚢',
	':rocket:': '🚀',
	':satellite:': '🛰️',
	':camera:': '📷',
	':phone:': '📱',
	':laptop:': '💻',
	':tv:': '📺',
	':watch:': '⌚',
	':clock:': '🕒',
	':lightbulb:': '💡',

	// 💬 Symbols
	':check:': '✅',
	':cross:': '❌',
	':warning:': '⚠️',
	':info:': 'ℹ️',
	':question:': '❓',
	':exclaim:': '❗',
	':up:': '⬆️',
	':down:': '⬇️',
	':left:': '⬅️',
	':right:': '➡️',
	':repeat:': '🔁',
	':infinity:': '♾️',
	':pause:': '⏸️',
	':play:': '▶️',
	':stop:': '⏹️',
	':record:': '⏺️',

	// 💡 Misc / Fun
	':brain:': '🧠',
	':moneybag:': '💰',
	':gem:': '💎',
	':book:': '📖',
	':pencil:': '✏️',
	':paint:': '🎨',
	':music:': '🎵',
	':headphones:': '🎧',
	':game:': '🎮',
	':dice:': '🎲',
	':robothead:': '🤖',
	':alien:': '👽',
	':planet:': '🪐',
	':spark:': '⚡',
	':boomsmoke:': '💨',
	':100:': '💯',
	':sleep:': '💤',
};
