import {
	HiOutlineEmojiHappy,
	HiOutlineFire,
	HiOutlineHeart,
	HiOutlineLightningBolt,
	HiOutlineMoon,
	HiOutlineMusicNote,
	HiOutlinePuzzle,
	HiOutlineSparkles,
	HiOutlineSun,
	HiOutlineTrendingUp,
} from 'react-icons/hi';
import { RiCake3Line, RiEmotionSadLine, RiGhostSmileLine } from 'react-icons/ri';
import { TbCoffee } from 'react-icons/tb';

export const MOODS = [
	{
		label: 'Happy',
		icon: HiOutlineEmojiHappy,
		color: 'text-amber-500',
		ringColor: 'ring-amber-200/30',
		bgColor: 'bg-amber-50/50',
		hoverRing: 'hover:ring-amber-300/40',
		activeRing: 'ring-amber-300/50',
		activeBg: 'bg-amber-50',
	},
	{
		label: 'Chill',
		icon: TbCoffee,
		color: 'text-orange-500',
		ringColor: 'ring-orange-200/30',
		bgColor: 'bg-orange-50/50',
		hoverRing: 'hover:ring-orange-300/40',
		activeRing: 'ring-orange-300/50',
		activeBg: 'bg-orange-50',
	},
	{
		label: 'Excited',
		icon: HiOutlineSparkles,
		color: 'text-emerald-500',
		ringColor: 'ring-emerald-200/30',
		bgColor: 'bg-emerald-50/50',
		hoverRing: 'hover:ring-emerald-300/40',
		activeRing: 'ring-emerald-300/50',
		activeBg: 'bg-emerald-50',
	},
	{
		label: 'Sad',
		icon: RiEmotionSadLine,
		color: 'text-blue-500',
		ringColor: 'ring-blue-200/30',
		bgColor: 'bg-blue-50/50',
		hoverRing: 'hover:ring-blue-300/40',
		activeRing: 'ring-blue-300/50',
		activeBg: 'bg-blue-50',
	},
	{
		label: 'Energetic',
		icon: HiOutlineLightningBolt,
		color: 'text-yellow-500',
		ringColor: 'ring-yellow-200/30',
		bgColor: 'bg-yellow-50/50',
		hoverRing: 'hover:ring-yellow-300/40',
		activeRing: 'ring-yellow-300/50',
		activeBg: 'bg-yellow-50',
	},
	{
		label: 'Romantic',
		icon: HiOutlineHeart,
		color: 'text-pink-500',
		ringColor: 'ring-pink-200/30',
		bgColor: 'bg-pink-50/50',
		hoverRing: 'hover:ring-pink-300/40',
		activeRing: 'ring-pink-300/50',
		activeBg: 'bg-pink-50',
	},
	{
		label: 'Hungry',
		icon: RiCake3Line,
		color: 'text-orange-500',
		ringColor: 'ring-orange-200/30',
		bgColor: 'bg-orange-50/50',
		hoverRing: 'hover:ring-orange-300/40',
		activeRing: 'ring-orange-300/50',
		activeBg: 'bg-orange-50',
	},
	{
		label: 'Musical',
		icon: HiOutlineMusicNote,
		color: 'text-purple-500',
		ringColor: 'ring-purple-200/30',
		bgColor: 'bg-purple-50/50',
		hoverRing: 'hover:ring-purple-300/40',
		activeRing: 'ring-purple-300/50',
		activeBg: 'bg-purple-50',
	},
	{
		label: 'Gaming',
		icon: HiOutlinePuzzle,
		color: 'text-indigo-500',
		ringColor: 'ring-indigo-200/30',
		bgColor: 'bg-indigo-50/50',
		hoverRing: 'hover:ring-indigo-300/40',
		activeRing: 'ring-indigo-300/50',
		activeBg: 'bg-indigo-50',
	},
	{
		label: 'Dreamy',
		icon: HiOutlineMoon,
		color: 'text-violet-500',
		ringColor: 'ring-violet-200/30',
		bgColor: 'bg-violet-50/50',
		hoverRing: 'hover:ring-violet-300/40',
		activeRing: 'ring-violet-300/50',
		activeBg: 'bg-violet-50',
	},
	{
		label: 'Spooky',
		icon: RiGhostSmileLine,
		color: 'text-slate-500',
		ringColor: 'ring-slate-200/30',
		bgColor: 'bg-slate-50/50',
		hoverRing: 'hover:ring-slate-300/40',
		activeRing: 'ring-slate-300/50',
		activeBg: 'bg-slate-50',
	},
	{
		label: 'Motivated',
		icon: HiOutlineTrendingUp,
		color: 'text-teal-500',
		ringColor: 'ring-teal-200/30',
		bgColor: 'bg-teal-50/50',
		hoverRing: 'hover:ring-teal-300/40',
		activeRing: 'ring-teal-300/50',
		activeBg: 'bg-teal-50',
	},
	{
		label: 'On Fire',
		icon: HiOutlineFire,
		color: 'text-red-500',
		ringColor: 'ring-red-200/30',
		bgColor: 'bg-red-50/50',
		hoverRing: 'hover:ring-red-300/40',
		activeRing: 'ring-red-300/50',
		activeBg: 'bg-red-50',
	},
	{
		label: 'Sunny',
		icon: HiOutlineSun,
		color: 'text-amber-400',
		ringColor: 'ring-amber-200/30',
		bgColor: 'bg-amber-50/50',
		hoverRing: 'hover:ring-amber-300/40',
		activeRing: 'ring-amber-300/50',
		activeBg: 'bg-amber-50',
	},
];

export const TAG_COLORS = [
	{ bg: 'bg-rose-50/70', text: 'text-rose-600', ring: 'ring-rose-200/30' },
	{ bg: 'bg-amber-50/70', text: 'text-amber-600', ring: 'ring-amber-200/30' },
	{ bg: 'bg-emerald-50/70', text: 'text-emerald-600', ring: 'ring-emerald-200/30' },
	{ bg: 'bg-sky-50/70', text: 'text-sky-600', ring: 'ring-sky-200/30' },
	{ bg: 'bg-violet-50/70', text: 'text-violet-600', ring: 'ring-violet-200/30' },
	{ bg: 'bg-pink-50/70', text: 'text-pink-600', ring: 'ring-pink-200/30' },
	{ bg: 'bg-indigo-50/70', text: 'text-indigo-600', ring: 'ring-indigo-200/30' },
	{ bg: 'bg-teal-50/70', text: 'text-teal-600', ring: 'ring-teal-200/30' },
	{ bg: 'bg-orange-50/70', text: 'text-orange-600', ring: 'ring-orange-200/30' },
	{ bg: 'bg-lime-50/70', text: 'text-lime-600', ring: 'ring-lime-200/30' },
];
