import {
	HiOutlineEmojiHappy,
	HiOutlineFire,
	HiOutlineHeart,
	HiOutlineLightningBolt,
	HiOutlineMoon,
	HiOutlineMusicNote,
	HiOutlinePuzzle,
	HiOutlineSparkles,
	HiOutlineSun,
	HiOutlineTrendingUp,
} from 'react-icons/hi';
import { RiCake3Line, RiEmotionSadLine, RiGhostSmileLine } from 'react-icons/ri';
import { TbCoffee } from 'react-icons/tb';

export const MOODS = [
	{
		label: 'Happy',
		icon: HiOutlineEmojiHappy,
		color: 'text-amber-500',
		ringColor: 'ring-amber-200/30',
		bgColor: 'bg-amber-50/50',
		hoverRing: 'hover:ring-amber-300/40',
		activeRing: 'ring-amber-300/50',
		activeBg: 'bg-amber-50',
	},
	{
		label: 'Chill',
		icon: TbCoffee,
		color: 'text-orange-500',
		ringColor: 'ring-orange-200/30',
		bgColor: 'bg-orange-50/50',
		hoverRing: 'hover:ring-orange-300/40',
		activeRing: 'ring-orange-300/50',
		activeBg: 'bg-orange-50',
	},
	{
		label: 'Excited',
		icon: HiOutlineSparkles,
		color: 'text-emerald-500',
		ringColor: 'ring-emerald-200/30',
		bgColor: 'bg-emerald-50/50',
		hoverRing: 'hover:ring-emerald-300/40',
		activeRing: 'ring-emerald-300/50',
		activeBg: 'bg-emerald-50',
	},
	{
		label: 'Sad',
		icon: RiEmotionSadLine,
		color: 'text-blue-500',
		ringColor: 'ring-blue-200/30',
		bgColor: 'bg-blue-50/50',
		hoverRing: 'hover:ring-blue-300/40',
		activeRing: 'ring-blue-300/50',
		activeBg: 'bg-blue-50',
	},
	{
		label: 'Energetic',
		icon: HiOutlineLightningBolt,
		color: 'text-yellow-500',
		ringColor: 'ring-yellow-200/30',
		bgColor: 'bg-yellow-50/50',
		hoverRing: 'hover:ring-yellow-300/40',
		activeRing: 'ring-yellow-300/50',
		activeBg: 'bg-yellow-50',
	},
	{
		label: 'Romantic',
		icon: HiOutlineHeart,
		color: 'text-pink-500',
		ringColor: 'ring-pink-200/30',
		bgColor: 'bg-pink-50/50',
		hoverRing: 'hover:ring-pink-300/40',
		activeRing: 'ring-pink-300/50',
		activeBg: 'bg-pink-50',
	},
	{
		label: 'Hungry',
		icon: RiCake3Line,
		color: 'text-orange-500',
		ringColor: 'ring-orange-200/30',
		bgColor: 'bg-orange-50/50',
		hoverRing: 'hover:ring-orange-300/40',
		activeRing: 'ring-orange-300/50',
		activeBg: 'bg-orange-50',
	},
	{
		label: 'Musical',
		icon: HiOutlineMusicNote,
		color: 'text-purple-500',
		ringColor: 'ring-purple-200/30',
		bgColor: 'bg-purple-50/50',
		hoverRing: 'hover:ring-purple-300/40',
		activeRing: 'ring-purple-300/50',
		activeBg: 'bg-purple-50',
	},
	{
		label: 'Gaming',
		icon: HiOutlinePuzzle,
		color: 'text-indigo-500',
		ringColor: 'ring-indigo-200/30',
		bgColor: 'bg-indigo-50/50',
		hoverRing: 'hover:ring-indigo-300/40',
		activeRing: 'ring-indigo-300/50',
		activeBg: 'bg-indigo-50',
	},
	{
		label: 'Dreamy',
		icon: HiOutlineMoon,
		color: 'text-violet-500',
		ringColor: 'ring-violet-200/30',
		bgColor: 'bg-violet-50/50',
		hoverRing: 'hover:ring-violet-300/40',
		activeRing: 'ring-violet-300/50',
		activeBg: 'bg-violet-50',
	},
	{
		label: 'Spooky',
		icon: RiGhostSmileLine,
		color: 'text-slate-500',
		ringColor: 'ring-slate-200/30',
		bgColor: 'bg-slate-50/50',
		hoverRing: 'hover:ring-slate-300/40',
		activeRing: 'ring-slate-300/50',
		activeBg: 'bg-slate-50',
	},
	{
		label: 'Motivated',
		icon: HiOutlineTrendingUp,
		color: 'text-teal-500',
		ringColor: 'ring-teal-200/30',
		bgColor: 'bg-teal-50/50',
		hoverRing: 'hover:ring-teal-300/40',
		activeRing: 'ring-teal-300/50',
		activeBg: 'bg-teal-50',
	},
	{
		label: 'On Fire',
		icon: HiOutlineFire,
		color: 'text-red-500',
		ringColor: 'ring-red-200/30',
		bgColor: 'bg-red-50/50',
		hoverRing: 'hover:ring-red-300/40',
		activeRing: 'ring-red-300/50',
		activeBg: 'bg-red-50',
	},
	{
		label: 'Sunny',
		icon: HiOutlineSun,
		color: 'text-amber-400',
		ringColor: 'ring-amber-200/30',
		bgColor: 'bg-amber-50/50',
		hoverRing: 'hover:ring-amber-300/40',
		activeRing: 'ring-amber-300/50',
		activeBg: 'bg-amber-50',
	},
];

export const TAG_COLORS = [
	{
		bg: 'bg-gradient-to-r from-violet-50 to-purple-50',
		text: 'text-violet-700',
		ring: 'ring-2 ring-violet-200/60',
		hover: 'hover:ring-violet-300',
	},
	{
		bg: 'bg-gradient-to-r from-blue-50 to-cyan-50',
		text: 'text-blue-700',
		ring: 'ring-2 ring-blue-200/60',
		hover: 'hover:ring-blue-300',
	},
	{
		bg: 'bg-gradient-to-r from-emerald-50 to-teal-50',
		text: 'text-emerald-700',
		ring: 'ring-2 ring-emerald-200/60',
		hover: 'hover:ring-emerald-300',
	},
	{
		bg: 'bg-gradient-to-r from-amber-50 to-yellow-50',
		text: 'text-amber-700',
		ring: 'ring-2 ring-amber-200/60',
		hover: 'hover:ring-amber-300',
	},
	{
		bg: 'bg-gradient-to-r from-rose-50 to-pink-50',
		text: 'text-rose-700',
		ring: 'ring-2 ring-rose-200/60',
		hover: 'hover:ring-rose-300',
	},
	{
		bg: 'bg-gradient-to-r from-indigo-50 to-blue-50',
		text: 'text-indigo-700',
		ring: 'ring-2 ring-indigo-200/60',
		hover: 'hover:ring-indigo-300',
	},
	{
		bg: 'bg-gradient-to-r from-teal-50 to-cyan-50',
		text: 'text-teal-700',
		ring: 'ring-2 ring-teal-200/60',
		hover: 'hover:ring-teal-300',
	},
	{
		bg: 'bg-gradient-to-r from-orange-50 to-red-50',
		text: 'text-orange-700',
		ring: 'ring-2 ring-orange-200/60',
		hover: 'hover:ring-orange-300',
	},
	{
		bg: 'bg-gradient-to-r from-fuchsia-50 to-pink-50',
		text: 'text-fuchsia-700',
		ring: 'ring-2 ring-fuchsia-200/60',
		hover: 'hover:ring-fuchsia-300',
	},
];

export const DICEBEAR_THEMES = [
	{ id: 'adventurer', name: 'Adventurer' },
	{ id: 'adventurer-neutral', name: 'Adventurer Neutral' },
	{ id: 'avataaars', name: 'Avataaars' },
	{ id: 'avataaars-neutral', name: 'Avataaars Neutral' },
	{ id: 'big-ears', name: 'Big Ears' },
	{ id: 'big-ears-neutral', name: 'Big Ears Neutral' },
	{ id: 'big-smile', name: 'Big Smile' },
	{ id: 'bottts', name: 'Bottts' },
	{ id: 'bottts-neutral', name: 'Bottts Neutral' },
	{ id: 'croodles', name: 'Croodles' },
	{ id: 'croodles-neutral', name: 'Croodles Neutral' },
	{ id: 'dylan', name: 'Dylan' },
	{ id: 'fun-emoji', name: 'Fun Emoji' },
	{ id: 'identicon', name: 'Identicon' },
	{ id: 'initials', name: 'Initials' },
	{ id: 'lorelei', name: 'Lorelei' },
	{ id: 'lorelei-neutral', name: 'Lorelei Neutral' },
	{ id: 'micah', name: 'Micah' },
	{ id: 'miniavs', name: 'Miniavs' },
	{ id: 'notionists', name: 'Notionists' },
	{ id: 'notionists-neutral', name: 'Notionists Neutral' },
	{ id: 'open-peeps', name: 'Open Peeps' },
	{ id: 'personas', name: 'Personas' },
	{ id: 'pixel-art', name: 'Pixel Art' },
	{ id: 'pixel-art-neutral', name: 'Pixel Art Neutral' },
	{ id: 'shapes', name: 'Shapes' },
	{ id: 'thumbs', name: 'Thumbs' },
];
export const DEFAULT_THEME = 'adventurer-neutral';
export const DEFAULT_API_VERSION = '9.x';
export const DEFAULT_RADIUS = 50;
